### ISSUE TITLE
Header oscillates when opening emojis on keyboard

### ISSUE THREAD

**Issue by yayabosh** [CommE2E/comm#155]
Opening the emojis on keyboard causes the header to oscillate quickly. Currently on iPhone 11 iOS 15.1.

https://user-images.githubusercontent.com/49079572/148439314-1c0de5ac-875a-49f9-8f2c-f15829ff40da.MP4

**Comment by Ashoat** [comment]
Thanks for the report @yayabosh!! If you don't mind, we'll close this and track it internally on our Linear install. It's actually something we've seen before but never had time to look into. (For anybody on the team's context, the original report is on [Notion](https://www.notion.so/commapp/iOS-App-Header-jumping-82cf4a3d3f6549388e71d58c3b107f1c))
