### ISSUE TITLE
xcode ios: failed to run custom build command for `native_rust_library v0.1.0`

### ISSUE THREAD

**Issue by denniswon** [CommE2E/comm#206]
I get the error 
```
failed to run custom build command for `native_rust_library v0.1.0`
```
When I try to build the native ios on my xcode. I am running a local keyserver, running metro server in the `native` folder (`yarn dev`), and I am building a development debug build using my signing certificates and provisioning profile.

I was following the dev env set up guide. Can someone help me resolve this issue?

**Comment by Ashoat** [comment]
I'm guessing you're missing some sort of dependency. The [Nix environment](https://github.com/CommE2E/comm/blob/master/docs/nix_dev_env.md) might be easier to set up... we might have missed some important step in the "mainline" [(old) dev environment](https://github.com/CommE2E/comm/blob/master/docs/dev_environment.md) instructions.

I think Xcode can show you more details on how the custom build command failed if you check the build logs:

<img width="489" alt="Screenshot 2023-01-13 at 8 31 11 PM" src="https://user-images.githubusercontent.com/863579/212448849-4ae92d8c-a46f-4f72-a0ec-a81df265ff8f.png">

**Comment by atulsmadhugiri** [comment]
If you're unable to see the full build logs in Xcode, you can try the following:

```
xcodebuild -workspace Comm.xcworkspace -scheme Comm -destination generic/platform=iOS
```

from `native/ios`.

I have a hunch it might be related to `native_rust_library`'s dependency on `protoc` (protocol buffer compiler) via the `prost` crate... but seeing the build logs would help narrow things down.

(As an aside, can you specify whether you're on an `arm64` or `x86` Mac?)

**Comment by denniswon** [comment]
Thanks @atulsmadhugiri I tried using `nix develop` instead, but now, I am getting

```
2023-01-15 18:57:38.186539+0900 Comm[12851:11085555] [unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
libc++abi: terminating with uncaught exception of type std::runtime_error: Failed to resolve database path - could not find groupUrl
Message from debugger: Terminated due to signal 6
```

This happens both in the physical device or simulator. Seems like it is having an issue with finding the sql db of the device. 

Any idea? I will try what you suggested above in the meantime. Thanks again for answering my questions.

**Comment by denniswon** [comment]
<img width="265" alt="Screenshot 2023-01-17 at 8 50 21 AM" src="https://user-images.githubusercontent.com/3278577/212781539-e65441d1-9513-4b8e-9124-738e0830a901.png">
I tried updating the app group name manually in the code to use the updated new app group name (from `app.comm.group` to `app.comm.group.dev`) but now that causes this error:

```
2023-01-16 16:14:07.716829+0900 Comm[49862:12453836] COMM: Failed to acquire lock. Details: File name too long
2023-01-16 16:14:07.739673+0900 Comm[49862:12453836] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600001b53c00> F8BB1C28-BAE8-11D6-9C31-00039315CD46
EXDevLauncher/ExpoDevLauncherAppDelegateSubscriber.swift:12: Fatal error: Cannot find the keyWindow. Make sure to call `window.makeKeyAndVisible()`.
2023-01-16 16:14:07.949019+0900 Comm[49862:12453836] EXDevLauncher/ExpoDevLauncherAppDelegateSubscriber.swift:12: Fatal error: Cannot find the keyWindow. Make sure to call `window.makeKeyAndVisible()`.
```

AppDelegate file does seem to be calling window.makeKeyAndVisible already, so don't think what I tried here is a valid thing to do.

Could someone from the team please help me out here? Trying to get the ios app running on either the simulator or the phone so that I can try out the app.

Thanks cc: @Ashoat @atulsmadhugiri

**Comment by Ashoat** [comment]
Hmm... I wonder if you need to create an App ID with Apple and register that group name. Do you have an Apple Developer account?

**Comment by denniswon** [comment]
@Ashoat I do and I did create an App ID on the dev console on apple, with app group capability. But did not register the group name. Maybe that's something that I missed.

**Comment by denniswon** [comment]
<img width="1253" alt="Screenshot 2023-01-17 at 3 19 08 PM" src="https://user-images.githubusercontent.com/3278577/212824035-1ca66560-8170-4c31-a0a0-72e83bec8390.png">
Actually, it is auto registered from xcode.

**Comment by denniswon** [comment]
```
2023-01-17 23:02:01.916538+0900 Comm[61163:14132061] COMM: Failed to acquire lock. Details: File name too long
2023-01-17 23:02:01.958319+0900 Comm[61163:14132061] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x60000133db40> F8BB1C28-BAE8-11D6-9C31-00039315CD46
EXDevLauncher/ExpoDevLauncherAppDelegateSubscriber.swift:12: Fatal error: Cannot find the keyWindow. Make sure to call `window.makeKeyAndVisible()`.
2023-01-17 23:02:02.232845+0900 Comm[61163:14132061] EXDevLauncher/ExpoDevLauncherAppDelegateSubscriber.swift:12: Fatal error: Cannot find the keyWindow. Make sure to call `window.makeKeyAndVisible()`.
Message from debugger: The LLDB RPC server has crashed. You may need to manually terminate your process. The crash log is located in ~/Library/Logs/DiagnosticReports and has a prefix 'lldb-rpc-server'. Please file a bug and attach the most recent crash log.
```

<img width="1172" alt="Screenshot 2023-01-17 at 11 06 04 PM" src="https://user-images.githubusercontent.com/3278577/212919550-e8fa2c47-109a-463a-a76e-a55617fff492.png">

**Comment by Ashoat** [comment]
I wonder what the filename that is too long is... could that be [something here](https://github.com/CommE2E/comm/blob/master/native/ios/Comm/TemporaryMessageStorage/NonBlockingLock.mm#L14)? Worth adding a breakpoint there to see if it triggers

**Comment by denniswon** [comment]
@Ashoat Thanks for the response. Now I am trying again with the breakpoint as you linked above, and also I changed all places where it was using hardcoded "app.comm" string to the new bundle id "app.comm.dev" that I am using for dev.

<img width="912" alt="Screenshot 2023-01-18 at 9 00 14 AM" src="https://user-images.githubusercontent.com/3278577/213038589-48390bf9-328e-4583-ab1d-2a0540b813ea.png">

The breakpoint does get hit, but after continuing, the same error occurs.

**Comment by marcinwasowicz** [comment]
Hi @denniswon !
Thank you for your comments and interest in our project!.
The error you are receiving: `COMM: Failed to acquire lock. Details: File name too long` stems from the fact that you updated `group.app.comm` to `group.app.comm` in `TemporaryMessageStorage.mm` file. What happens here? When application starts it seeks for notifications persisted in a temporary flat file by NotificationService. In order to avoid race condition between an application and NotificationService at app start, we synchronize access to this file with POSIX semaphore. POSIX semaphores must be initialized with a name whose length is limited by OS. Additionally Apple suggests that name of semaphores shared by processes in the same app group start with its identifier as a prefix (although it is not a hard requirement as I remember). By adding `.dev` infix you simply exceeded the limit OS gives on the name of a semaphore. I suggest not changing hardcoded `group.app.comm` in `TemporaryMessageStorage.mm`.

**Comment by marcinwasowicz** [comment]
Hi @denniswon !
Changing `group.app.comm` to `group.app.comm.dev` was a right step, but the only place where you should keep `group.app.comm` is `_getLockName` method in `TemporaryMessageStorage.mm`. The reason for that is this method returns name for a semaphore. OS provides an upper limit on the length of the name of the semaphore and looks like adding `.dev` infix makes it exceed this limit. Additionally I recall that adding group name prefix for a semaphore name wasn't hard requirement, but rather suggestion by apple.So you should keep the changes you already did, but just make sure that `_getLockName` method still uses `group.app.comm` prefix without `.dev`. Let me know if it solves your problem!

**Comment by vdhanan** [comment]
Closing, but feel free to re-open if you have any more questions!
