### ISSUE TITLE
please stop paging me with @ mentions

### ISSUE THREAD

**Issue by inka** [CommE2E/comm#312]
Hi,

your are using "@inka" a lot and I get a notification each time. Can you please stop that.
I really do not like to disable my notifications for mentions in general.

Docs:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#mentioning-people-and-teams

Thanks and happy coding,
inka

**Comment by Ashoat** [comment]
It's unfortunate that GitHub doesn't offer a way to disable this on a per-repo level. It's a lot to ask for people to people to work around it in their Git commit messages. We use a different system for code review where somebody on our team has the username "@inka", and the tagging there is necessary to CC that user.
