### ISSUE TITLE
Pasting image on iOS

### ISSUE THREAD

**Issue by Ashoat** [CommE2E/comm#72]
Some context in https://github.com/react-native-community/clipboard/issues/6. On iOS it's possible to copy an image from one app to another, but support isn't really there in React Native, so we'll have to work on a native module.

We should support pasting an image into `ChatInputBar`, but to do this right we'll need some sort of "staging area" so the user gets to see their image before it sends.

**Comment by atulsmadhugiri** [comment]
- [ ] Finish separating ImagePasteModal into it's own independent component
- [ ] Changing modal background based on light/dark mode
- [ ] Deleting image file on cancel
- [ ] Deleting image file after successful upload
- [ ] Increase spacing between 'send' and 'cancel' to prevent misclicks
- [ ] Ensure that image pastes from browser don't fill up text input with URL

**Comment by Ashoat** [comment]
This is done!!!
